version: '3.3'

services:
  mysql8:
    image: mysql:8.0.16
    ports:
     - "3600:3600"
    volumes:
     - mysql_data:/var/lib/mysql
     - /home/ubuntu/docker/volumes/etc/my.cnf:/etc/my.cnf
     - mysql_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db.test-1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql8
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
       WORDPRESS_DB_HOST: mysql8:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    mysql_data: {}
    mysql_log: {}
